
[Interface]
Address = 10.101.0.42/32
PrivateKey = eNEqX2J7Q92HTQm3AcO3a6obEWXWBeEjfJTqUfnWJH8=
PostUp = printf 'You can now access http://0.0.0.0:3000 on https://ekdte9.tunnel.pyjam.as/ ✨\n'

[Peer]
PublicKey = R3dT/EU7n/FMoow9gUjjc0qzTN0K7uqQSrmLgABsITA=
AllowedIPs = 10.101.0.1/32
Endpoint = tunnel.pyjam.as:55555
PersistentKeepalive = 21
