
[Interface]
Address = 10.101.0.20/32
PrivateKey = qJk+5ukp0tgsrWVyZce3IU6fZ1zF3yvCTZ5qZTGrLXE=
PostUp = printf 'You can now access http://0.0.0.0:3000 on https://e56emk.tunnel.pyjam.as/ ✨\n'

[Peer]
PublicKey = F18OXhxsVebsZ8HwVn8a2L6ye3F3JFSIviPf44iInzc=
AllowedIPs = 10.101.0.1/32
Endpoint = tunnel.pyjam.as:55555
PersistentKeepalive = 21
