
[Interface]
Address = 10.101.0.76/32
PrivateKey = 6C+NNq0IqTCdUoNkhdbU75faHvyQNMl6B/MAS6k1anU=
PostUp = printf 'You can now access http://0.0.0.0:3000 on https://i8abfz.tunnel.pyjam.as/ ✨\n'

[Peer]
PublicKey = 4C4BVMf0pGcPBgyVLNkAn0ntjUc2haGm+Ei6QRnmBwQ=
AllowedIPs = 10.101.0.1/32
Endpoint = tunnel.pyjam.as:55555
PersistentKeepalive = 21
